language: cpp

notifications:
  email: false
  
compiler: gcc

dist: trusty

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install -y valgrind libeigen3-dev
  
script:   
- valgrind --leak-check=yes open
