language: cpp

notifications:
  email: false
  
compiler: gcc

dist: trusty

cache:
  apt: true
  directories:
    - "$HOME/.cache/pip"
    - "$HOME/.cache/nvim-deps"

before_install:
  - sudo apt-get install -y valgrind
  
script:   
  - valgrind --leak-check=yes open

after_script:
  - echo "good build"
