language: cpp

notifications:
  email: false

cache:
  apt: true
  directories:
    - "$HOME/.cache/pip"
    - "$HOME/.cache/nvim-deps"

before_install:
  - sudo apt-get install -y valgrind
  
script:
  - g++ -g for_lint.cpp
  - valgrind --leak-check=yes ./a.out

after_script:
  - echo "It's OK! (:"
