language: cpp

sudo: false

notifications:
  email: false

install:
  - pip install pyflakes
  - pip install cpplint
  - pip install cppcheck
  - pip install oclint
  
script:   
- cpplint for_lint.cpp
- cppcheck for_lint.cpp
- oclint for_lint.cpp
