language: cpp

notifications:
  email: false

matrix:
  include:

    # Linux C++14 GCC builds
    - os: linux
      addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-6
          - g++-6
          - valgrind
      env: get ubuntu-toolchain
  
script:   
- valgrind --leak-check=yes -v ./open
